name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: pvchaitanya8
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=#2563eb&color_dots=#0f172a,#1e293b,#2563eb,#38bdf8,#93c5fd&color_background=#020617

      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
